apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: conta-ms-fernandoe-com
  namespace: default
spec:
  secretName: conta-ms-fernandoe-com-tls
  issuerRef:
    name: ca-issuer
    kind: Issuer
  commonName: conta.ms.fernandoe.com
  dnsNames:
  - conta.ms.fernandoe.com
