apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: "fer.esp@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-production
    http01: {}
