apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pessoa-ms-fernandoe-com
  namespace: default
spec:
  secretName: pessoa-ms-fernandoe-com-tls
  issuerRef:
    name: letsencrypt-production
  commonName: pessoa.ms.fernandoe.com
  dnsNames:
  - pessoa.ms.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - pessoa.ms.fernandoe.com
