apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-pessoa
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: 1-deploy-pessoa
        service: pessoa
    spec:
      containers:
      - name: fe-pessoa
        image: fernandoe/fe-pessoa-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: 'server.settings.docker'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fe-pessoa
                key: database_url
