


#$ kubectl create -f es-statefulset.yaml
#$ kubectl create -f es-service.yaml
#$ kubectl create -f fluentd-es-configmap.yaml
#$ kubectl create -f fluentd-es-ds.yaml
#$ kubectl create -f kibana-deployment.yaml
#$ kubectl create -f kibana-service.yaml