version: "3"

services:
  mysql:
    container_name: fe.devstack.mysql
    image: mysql:5.7.21
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

  conta:
    container_name: fe.devstack.conta
    image: fernandoe/fe-conta-server:local
    ports:
      - "9000:8000"
    volumes:
      - ../fe-conta-server/src:/app
    depends_on:
      - mysql
    environment:
       DATABASE_URL: mysql://root:password@mysql:3306/fe_conta
       no_proxy: mysql
    stdin_open: true
    tty: true

  pessoa:
    container_name: fe.devstack.pessoa
    image: fernandoe/fe-pessoa-server:local
    ports:
      - "9001:8000"
    volumes:
      - ../fe-pessoa-server/src:/app
    depends_on:
      - mysql
      - conta
    environment:
      DJANGO_SETTINGS_MODULE: 'server.settings.docker'
      DATABASE_URL: mysql://root:password@mysql:3306/fe_pessoa
      no_proxy: mysql,conta
    stdin_open: true
    tty: true

  web:
    container_name: fe.devstack.web
    build:
      context: ../fe-server
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ../fe-server:/app
    environment:
      no_proxy: conta,pessoa
    depends_on:
      - conta
      - pessoa

volumes:
  mysql-data:
