create.ingress:
	kubectl create -f ./ingress.yaml

create.ingress-nginx:
	kubectl create -f ./ingress-nginx.yaml

create.nginx-default-backend:
	kubectl create -f ./nginx-default-backend.yaml

apply.ingress:
	kubectl apply -f ./ingress.yaml

apply.ingress-nginx:
	kubectl apply -f ./ingress-nginx.yaml

apply.nginx-default-backend:
	kubectl apply -f ./nginx-default-backend.yaml

apply.all: apply.ingress apply.ingress-nginx apply.nginx-default-backend
