apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sms-ms-fernandoe-com
spec:
  secretName: sms-ms-fernandoe-com-tls
  issuerRef:
    name: letsencrypt-production
  commonName: sms.ms.fernandoe.com
  dnsNames:
  - sms.ms.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - sms.ms.fernandoe.com
