apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-pagamento
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: 1-deploy-pagamento
        service: pagamento
    spec:
      containers:
      - name: fe-pagamento
        image: fernandoe/fe-pagamento-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: 'server.settings.docker'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fe-pagamento
                key: database_url
