apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deploy-server
    spec:
      containers:
      - name: fe-server
        image: fernandoe/fe-server
        ports:
        - containerPort: 80
