apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-endereco
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: 1-deploy-endereco
        service: endereco
    spec:
      containers:
      - name: fe-endereco
        image: fernandoe/fe-endereco-server:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: 'server.settings.docker'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fe-endereco
                key: database_url
