apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: pagamento-ms-fernandoe-com
spec:
  secretName: pagamento-ms-fernandoe-com-tls
  issuerRef:
    name: letsencrypt-production
  commonName: pagamento.ms.fernandoe.com
  dnsNames:
  - pagamento.ms.fernandoe.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - pagamento.ms.fernandoe.com
