apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-sms
  labels:
    app: send-sms
spec:
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: fe-sms-server
            image: fernandoe/fe-sms-server:feature-enviar-mensagem
            imagePullPolicy: Always
            args:
            - /bin/sh
            - -c
            - make sendsms
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: 'server.settings.docker'
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: fe-sms
                    key: database_url
              - name: AWS_DEFAULT_REGION
                value: us-west-2
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: fe-sms
                    key: AWS_ACCESS_KEY_ID
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: fe-sms
                    key: AWS_SECRET_ACCESS_KEY
          restartPolicy: OnFailure
