apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fe-sms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: 1-deploy-sms
    spec:
      containers:
      - name: fe-sms
        image: fernandoe/fe-sms-server:feature-enviar-mensagem
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: 'server.settings.docker'
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fe-sms
                key: database_url
