apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sms
spec:
  selector:
    matchLabels:
      service: sms
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: web
    interval: 30s
